version: 0.2

phases:

  pre_build:
    commands:
      - echo this is the login step
      - docker login -u=naveen09 -p=Absolution999

  build:
    commands:
      - docker build -t xorianttestapp:1.4 .
      - docker tag xorianttestapp:1.4 naveen09/xorianttestapp:1.4

  post_build:
    commands:
      - docker run -it xorianttestapp:1.4 ./carta-devops test
      - docker push naveen09/xorianttestapp:1.4
