apiVersion: v1
kind: Pod
metadata:
  name: xoriantapppod
  labels:
    name: webapp
    type: webapp-frontend
spec:
  containers:
    - name: xoriantapppod
      image: naveen09/xorianttestapp:1.3
      command: ["python" , "app/web.py"]
  restartPolicy: OnFailure
